parameters:
#    cerad_app.example.class: Cerad\Bundle\AppBundle\Example

services:
#    cerad_app.example:
#        class: %cerad_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    cerad_tourn.schedule_search.form_type:
        class: Cerad\Bundle\AppBundle\FormType\Schedule\Search\SearchFormType
        tags:
            - { name: form.type, alias: cerad_schedule_search }

    cerad_tourn.excel:
        class:  Cerad\Component\Excel\Excel
            
    cerad_tourn.schedule_official_search.export_csv:
        class:  Cerad\Bundle\AppBundle\Schedule\Search\ScheduleSearchExportCSV

    cerad_tourn.schedule_official_search.export_xls:
        class:  Cerad\Bundle\AppBundle\Schedule\Search\ScheduleSearchExportXLS
        arguments:  
            - '@cerad_tourn.excel'
    
    cerad_tourn.schedule_my.export_csv:
        class:  Cerad\Bundle\AppBundle\Schedule\My\ScheduleMyExportCSV

    cerad_tourn.schedule_my.export_xls:
        class:  Cerad\Bundle\AppBundle\Schedule\My\ScheduleMyExportXLS
        arguments:  
            - '@cerad_tourn.excel'
    
    cerad_tourn.schedule_search.export_csv:
        class:  Cerad\Bundle\AppBundle\Schedule\Search\ScheduleSearchExportCSV

    cerad_tourn.schedule_search.export_xls:
        class:  Cerad\Bundle\AppBundle\Schedule\Search\ScheduleSearchExportXLS
        arguments:  
            - '@cerad_tourn.excel'
            
    cerad_tourn.officials.export_xls:
        class:  Cerad\Bundle\AppBundle\Officials\ExportOfficialsXLS
        arguments:  
            - '@cerad_tourn.excel'
            - '@cerad_org.org_repository'
            
    cerad_tourn.schedule_officials.import_xls:
        class:  Cerad\Bundle\TournAdminBundle\Schedule\Officials\ScheduleOfficialsImportXLS
        arguments:  
            - '@cerad_game.game_repository'
            - '@cerad_person.person_repository'
            
    cerad_tourn.results.export_xls:
        class:  Cerad\Bundle\AppBundle\Results\ResultsExportXLS
        arguments:  
            - '@cerad_tourn.excel'
    #
    #cerad_tourn_admin.persons.export_xls:
    #    class: Cerad\Bundle\AppAdminBundle\Services\Persons\PersonsExportXLS
    #    
    ## s1games compatibility
    #cerad_tourn.officials.export_xls:
    #    class: Cerad\Bundle\AppAdminBundle\Services\Persons\PersonsExportXLS
    #    arguments:  
    #        - '@cerad_tourn.excel'
    #        - '@cerad_org.org_repository'

# Twig extensions
    cerad_app.twig_extension:
        class:  Cerad\Bundle\AppBundle\TwigExtension\AppExtension
        arguments:  
            - '@cerad_project.find_default.in_memory'
        tags:
            - { name: twig.extension }

    cerad_org.twig_extension:
        class:  Cerad\Bundle\AppBundle\TwigExtension\OrgExtension
        arguments:  
            - '@cerad_org.org_repository'
        tags:
            - { name: twig.extension }            