parameters:
#    cerad_app.example.class: Cerad\Bundle\AppBundle\Example

services:
#    cerad_app.example:
#        class: %cerad_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    cerad_tourn.schedule_search.form_type:
        class: Cerad\Bundle\AppBundle\FormType\Schedule\Search\SearchFormType
        tags:
            - { name: form.type, alias: cerad_schedule_search }