AYSOS1GamesLowerSpring2014:  
    info:
        id: AYSOS1GamesLowerSpring2014
        group: AYSOS1GamesLower
        slugs:
            - s1games
            - s1game2014
            
        status:   Active
        verified: Yes
                
        fedId:     AYSO
        fedRoleId: AYSOV
                
        title:   "AYSO Section One U10/U12/U14 Games 2014"
        desc:    "AYSO Section One U10/U12/U14 Games -- Ab Brown Complex, Riverside -- 22-23 Feb & 1-2 Mar 2014"
                          
        results: s1games

        submit:  "Emails your application to Art Hundiak and yourself."
        prefix:   S1Games
             
        assignor:
            name:  "Jody Kinsey"
            email: "jodykinsey23@gmail.com"
            phone:  909.262.8806

        system:
            name:  "Section One U10/U12/U14 Games 2014"
            email: "no.response.s1games@gmail.com"
            phone:  ""        
        
    # ==============================================
    # Hidden from the schedule search form
    #do_not_searches:
    #
    #  dates:
    #    type:     checkbox
    #    label:    Days
    #    default: ['All','2014-02-22','2014-02-23','2014-03-01','2014-03-02']
    #    choices:
    #      'All'       : All
    #      '2014-02-22': Sat 2/23
    #      '2014-02-23': Sun 2/23
    #      '2014-03-01': Sat 3/01
    #      '2014-03-02': Sun 3/02
    #      
    #  league:
    #    type:     checkbox
    #    label:    League
    #    default:  [All, AYSO_U10B_League, AYSO_U10G_League, AYSO_U12B_League, AYSO_U12G_League, AYSO_U14B_League, AYSO_U14G_League]
    #    choices:
    #      'All'     : All
    #      'AYSO_U10B_League'   : U10B
    #      'AYSO_U10G_League'   : U10G
    #      'AYSO_U12B_League'   : U12B
    #      'AYSO_U12G_League'   : U12G
    #      'AYSO_U14B_League'   : U14B
    #      'AYSO_U14G_League'   : U14G
    #      
    #  allstar:
    #    type:     checkbox
    #    label:    All-Star
    #    default: [All,AYSO_U10B_AllStars,AYSO_U10G_AllStars,AYSO_U12B_AllStars,AYSO_U12G_AllStars,AYSO_U14B_AllStars,AYSO_U14G_AllStars]
    #    choices:
    #      'All'     : All
    #      'AYSO_U10B_AllStars' : U10B
    #      'AYSO_U10G_AllStars' : U10G
    #      'AYSO_U12B_AllStars' : U12B
    #      'AYSO_U12G_AllStars' : U12G
    #      'AYSO_U14B_AllStars' : U14B
    #      'AYSO_U14G_AllStars' : U14G
    #      
    #  extra:
    #    type:     checkbox
    #    label:    Extra
    #    default:  [All,AYSO_U10B_Extra,AYSO_U10G_Extra,AYSO_U11B_Extra,AYSO_U11G_Extra,AYSO_U12B_Extra,AYSO_U12G_Extra,AYSO_U13B_Extra,AYSO_U13G_Extra,AYSO_U14B_Extra,AYSO_U14G_Extra]
    #    choices:
    #      'All'     : All
    #      'AYSO_U10B_Extra'    : U10B
    #      'AYSO_U10G_Extra'    : U10G
    #      'AYSO_U11B_Extra'    : U11B
    #      'AYSO_U11G_Extra'    : U11G
    #      'AYSO_U12B_Extra'    : U12B
    #      'AYSO_U12G_Extra'    : U12G
    #      'AYSO_U13B_Extra'    : U13B
    #      'AYSO_U13G_Extra'    : U13G
    #      'AYSO_U14B_Extra'    : U14B
    #      'AYSO_U14G_Extra'    : U14G
    #      
      
    # ==============================================
    # For the schedule search form
    searches:
      
      #dow:
      #  type:     checkbox
      #  label:    Day of Week
      #  default: ['All','2014-02-22,2014-03-02','2014-02-23,2014-03-02']
      #  choices:
      #    All   : All
      #    #'Fri'   : Fri
      #    2014-02-22, 2014-03-02   : Sat
      #    2014-02-23, 2014-03-02   : Sun
      
      # Added these back in, only super admin (art) will see them
      dates:
          type:     checkbox
          label:    Days
          default: ['All','2014-02-22','2014-02-23','2014-03-01','2014-03-02']
          choices:
              'All'       : All
              '2014-02-22': Sat 2/23
              '2014-02-23': Sun 2/23
              '2014-03-01': Sat 3/01
              '2014-03-02': Sun 3/02
          
      programs:
        type:     checkbox
        label:    Programs
        default:  ['League']
        choices:
          All      : All
          League   : League
          AllStars : All Stars
          Extra    : Extra
          
      genders:
        type:     checkbox
        label:    Genders
        default:  [All, B,G]
        choices:
          All:  All
          B:    Boys
          G:    Girls
          
      ages:
        type:     checkbox
        label:    Ages
        default:  [All, 'U10','U11,U12','U13,U14']
        choices:
          All:     All
          U10:     U10
          U11,U12: U12
          U13,U14: U14
        
      fields:
        type:    checkbox
        label:   Fields
        default: [All,'Blue 1','Blue 2','Blue 3','Blue 4','Blue 5','Green 1','Green 2','Green 3','Murphy 1','Murphy 2','Red 1','Red 2','White 1','White 2','White 3','White 4','Yellow 1','Yellow 2','Yellow 3']
        choices:
          'All'     : All
          'Blue 1' : 'Blue1'
          'Blue 2' : 'Blue2'
          'Blue 3' : 'Blue3'
          'Blue 4' : 'Blue4'
          'Blue 5' : 'Blue5'
          'Green 1' : 'Green1'
          'Green 2' : 'Green2'
          'Green 3' : 'Green3'
          'Murphy 1' : 'Murphy1'
          'Murphy 2' : 'Murphy2'
          'Red 1' : 'Red1'
          'Red 2' : 'Red2'
          'White 1' : 'White1'
          'White 2' : 'White2'
          'White 3' : 'White3'
          'White 4' : 'White4'
          'Yellow 1' : 'Yellow1'
          'Yellow 2' : 'Yellow2'
          'Yellow 3' : 'Yellow3'
        
    #times: # Want this to be a select
    #  start: 0600
    #  end:   2000
    
     #venues:
     #  type:    checkbox
     #  label:   Venues
     #  default: AB
     #  choices:
     #    AB: Ab Brown Soccer Complex, Riverside
    
    # ==================================================
    # Basic volunteer plan
    basic:
      attending:
        type:    select
        label:   I will attend
        default: na
        choices:
          na:    Not yet answered
          no:    No
          we12:  Both Weekends
          we1:   1st weekend only - League
          we2:   2nd weekend only - All Star/Extra
          maybe: Maybe
          
     #attendingLeague:
     #  type:    select
     #  label:   I will attend the League Playoffs
     #  default: na
     #  choices:
     #    na:    Not yet answered
     #    no:    No
     #    yes:   Yes - For Sure
     #    yesx:  Yes - If my team is selected
     #    maybe: Maybe
          
     #attendingASExtra:
     #  type:    select
     #  label:   I will attend the All-Star/Extra Playoffs
     #  default: na
     #  choices:
     #    na:    Not yet answered
     #    no:    No
     #    yes:   Yes - For Sure
     #    yesx:  Yes - If my team is selected
     #    maybe: Maybe
                    
      refereeing:
        type:    select
        label:   I will referee
        default: yes
        choices: { no: No, yes: Yes, maybe: Not Sure }
        
      #venue:
      #  type:    select
      #  label:   I will work at
      #  default: na
      #  choices: 
      #    na:    Not yet answered
      #    core:  Torrance/Redondo Beach (CORE site)
      #    extra: Riverside (EXTRA site)
      #    other: Where needed (either site)
           
#     refLevelCR:
#       type:    select
#       label:   Level to center at
#       default: na
#       choices: { na: na, U10: U10, U12: U12, U14: U14, U16: U16, U19: U19
             
#     refLevelAR:
#       type:    select
#       label:   Level to assist at
#       default: na
#       choices: { na: na, U10: U10, U12: U12, U14: U14, U16: U16, U19: U19
             
      #willInstruct:
      #  type:    select
      #  label:   I am certified Instructor
      #  default: no
      #  choices: { no: No, ri: Referee Instructor, ari: Advanced Referee Instructor, nri: National Referee Instructor}
      #     
      #willAssess:
      #  type:    select
      #  label:   I am certified Assessor
      #  default: no
      #  choices: { no: No, ra: Referee Assessor, nra: National Referee Assessor}
      #     
      willMentor:
        type:    select
        label:   I will be available as a mentor
        default: no
        choices: { no: No, yes: Yes }
           
      wantMentor:
        type:    select
        label:   I would like to work with a mentor
        default: no
        choices: { no: No, yes: Yes }
           
      #willAssess:
      #  type:    select
      #  label:   I will do assessments/observations
      #  default: no
      #  choices: { no: No, yes: Yes, maybe: Not Sure \}
      #     
      #wantAssess:
      #  type:    select
      #  label:   I request an assessment or observation
      #  default: no
      #  choices: 
      #    no:           No 
      #    Informal:     Informal 
      #    Intermediate: Intermediate
      #    AdvancedCR:   Advanced CR
      #    AdvancedAR:   Adcanced AR
      #    AdvancedCRAR: Advanced CR and AR
      #    NationalCR:   National CR
      #    NationalAR:   Advanced AR
      #    NationalCRAR: National CR and AR
             
      coaching:
        type:    select
        label:   I will coach or manage a team
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
           
      volunteering:
        type:    select
        label:   I will volunteer for other jobs
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
           
      playing:
        type:    select
        label:   I have (or am) a player in the games
        default: no
        choices: { no: No, yes: Yes, player: Yes - I am a player }
           
      #opening:
      #  type:    select
      #  label:   I will attend the Tuesday Night Opening Ceremony?
      #  default: no
      #  choices: { no: No, yesRAL: Yes in Riverside, yesTOA: Yes in Torrance, maybe: Not Sure \}
      #  
      #tshirt:
      #  type:    select
      #  label:   T-Shirt Size
      #  default: na
      #  choices: 
      #    na:        na
      #    youthm:    Youth Medium 
      #    youthl:    Youth Large
      #    adults:    Adult Small
      #    adultm:    Adult Medium
      #    adultl:    Adult Large
      #    adultlx:   Adult Large X
      #    adultlxx:  Adult Large XX
      #       
      #shuttle:
      #  type:    select
      #  label:   I need shuttle service during the games
      #  default: no
      #  choices: { no: No, yes: Yes, maybe: Not Sure \}
      #     
      #housing:
      #  type:    select
      #  label:   I would use low cost referee housing
      #  default: no
      #  choices: { no: No, yes: Yes, maybe: Not Sure \}
      #     
      #hotel:
      #  type:  text
      #  label: Hotel staying at
      #  size:  30
        
      notes:
        type:  textarea
        label: Notes
        rows:  5
        cols:  40
        
    # Break out availability
    avail:
      
      #AvailWen:
      #  type:    select
      #  label:   Available Wednesday (Jamborees)
      #  default: no
      #  choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure }
      #     
      #AvailThu:
      #  type:    select
      #  label:   Available Thursday (Pool Play)
      #  default: no
      #  choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure }
      #
      #AvailFri:
      #  type:    select
      #  label:   Available Friday (Pool Play)
      #  default: no
      #  choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure }
      #
      AvailSat22_08-11:
        type:    select
        label:   Available League Saturday Morning (8:00-10:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
           
      AvailSat22_11-14:
        type:    select
        label:   Available League Saturday Mid-day (11:0-13:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSat22_14-17:
        type:    select
        label:   Available League Saturday Afternoon (14:00-17:00 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSun23_08-11:
        type:    select
        label:   Available League Sunday Morning (8:00-10:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
           
      AvailSun23_11-14:
        type:    select
        label:   Available League Sunday Mid-day (11:0-13:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSun23_14-17:
        type:    select
        label:   Available League Sunday Afternoon (14:00-17:00 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSat01_08-11:
        type:    select
        label:   Available AS/Extra Saturday Morning (8:00-10:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
           
      AvailSat01_11-14:
        type:    select
        label:   Available AS/Extra Saturday Mid-day (11:0-13:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSat01_14-17:
        type:    select
        label:   Available AS/Extra Saturday Afternoon (14:00-17:00 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSun02_08-11:
        type:    select
        label:   Available AS/Extra Sunday Morning (8:00-10:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
           
      AvailSun02_11-14:
        type:    select
        label:   Available AS/Extra Sunday Mid-day (11:0-13:59 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }

      AvailSun02_14-17:
        type:    select
        label:   Available AS/Extra Sunday Afternoon (14:00-17:00 Kickoff)
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
 
