parameters:
    
  cerad_level_level_files:
    - "%cerad_app_resources_dir%/config/levels/ayso_league.yml"
    - "%cerad_app_resources_dir%/config/levels/ayso_allstars.yml"
    - "%cerad_app_resources_dir%/config/levels/ayso_extra.yml"          