parameters:
    
    cerad_level_level_files:
        - "%kernel_dir%/config/levels/ayso_league.yml"
        - "%kernel_dir%/config/levels/ayso_allstar.yml"
        - "%kernel_dir%/config/levels/ayso_extra.yml"          