parameters:

    #cerad_project_project_default: AYSOS1GamesUpperFall2013
    cerad_project_project_default: AYSOS1GamesLowerSpring2014
    
    cerad_project_project_files:
        - "%kernel.root_dir%/config/projects/AYSOS1GamesLowerSpring2014.yml"
        - "%kernel.root_dir%/config/projects/AYSOS1GamesUpperFall2013.yml"