# 17 Jan 2014
# Want to start using the TournBundle routes
# Still override if needed

cerad_tourn:
    resource: "@CeradTournBundle/Resources/config/routing.yml"
    prefix:   /
    
cerad_tourn_admin:
    resource: "@CeradTournAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
cerad_app:
    resource: "@CeradAppBundle/Resources/config/routing.yml"
    prefix:   /

cerad_app_admin:
    resource: "@CeradAppBundle/Resources/config/routing_admin.yml"
    prefix:   /
