parameters:
  
    cerad_tourn_show_configs:
      
        rick:
            layout_header:  true
            layout_topmenu: true
            layout_userinfo: true
            janrain:        false  # Social network login
            wordpress:      true  # Style sheets and javascripts
            
        default:
            layout_header:  true
            layout_topmenu: true
            layout_userinfo: true
            janrain:        false #true
            wordpress:      true  #false
            
